# Generated by Django 6.0.6 on 2026-06-08 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Banda Mariscos', max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Historia y esencia de la banda')),
                ('founded_date', models.DateField(help_text='Fecha de creación de la banda')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='band/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_whatsapp', models.CharField(blank=True, help_text='Número con código de país', max_length=20)),
                ('youtube_channel_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información de la Banda',
                'verbose_name_plural': 'Información de la Banda',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text='ID del video de YouTube (ej: dQw4w9WgXcQ)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar en sección principal')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.bandinfo')),
            ],
            options={
                'verbose_name': 'Video de YouTube',
                'verbose_name_plural': 'Videos de YouTube',
                'ordering': ['order', '-published_at'],
            },
        ),
    ]
