# Generated by Django 6.0.6 on 2026-06-08 04:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('intro_outro', 'Intros y Outros para Contenido Digital'), ('custom_song', 'Corrido o Canción por Encargo'), ('soundscape', 'Paisajes Sonoros (Audio Ambiente)'), ('soundbite', 'Frases con Sabor / Sound Bites')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio fijo en MXN. Ej: 1500.00', max_digits=10)),
                ('clip_link', models.URLField(blank=True, help_text='Link de pago de Clip para este servicio')),
                ('duration_info', models.CharField(blank=True, help_text='Ej: 5-10 segundos', max_length=100)),
                ('includes', models.JSONField(default=list, help_text='Lista de lo que incluye el servicio')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono o emoji representativo', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe contener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('details', models.TextField(help_text='Historia, datos del negocio, dedicatoria, etc.', verbose_name='Detalles del proyecto')),
                ('reference_links', models.TextField(blank=True, help_text='YouTube, Spotify, ejemplos de estilo deseado', verbose_name='Links de referencia')),
                ('urgency', models.CharField(choices=[('low', 'Sin prisa'), ('normal', 'Normal (1-2 semanas)'), ('high', 'Urgente (menos de 1 semana)')], default='normal', max_length=20, verbose_name='Urgencia')),
                ('status', models.CharField(choices=[('pending_payment', 'Pago Pendiente'), ('paid', 'Pagado'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='services.service')),
            ],
            options={
                'verbose_name': 'Solicitud de Contratación',
                'verbose_name_plural': 'Solicitudes de Contratación',
                'ordering': ['-created_at'],
            },
        ),
    ]
