# Generated by Django 5.0.14 on 2026-06-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de Cotización', 'verbose_name_plural': 'Solicitudes de Cotización'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='clip_link',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='budget_hint',
            field=models.CharField(blank=True, max_length=100, verbose_name='Presupuesto aproximado'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_range',
            field=models.CharField(blank=True, help_text='Ej: Desde $1,500 MXN', max_length=100),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('in_progress', 'En proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
